# This rule is not used by the project kube-crd-kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.kwatch.cloudcorner.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-crd-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: kwatcher-viewer-role
rules:
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers/status
  verbs:
  - get
