apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kwatcher-operator.fullname" . }}-kwatcher-admin-role
  labels:
  {{- include "kwatcher-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers
  verbs:
  - '*'
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers/status
  verbs:
  - get