apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kwatcher-operator.fullname" . }}-manager-role
  labels:
  {{- include "kwatcher-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - core.kwatch.cloudcorner.org
  resources:
  - kwatchers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kwatcher-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kwatcher-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kwatcher-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kwatcher-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'